;; -*- no-byte-compile: t; -*-
;;; private/amos/packages.el
(package! evil-commentary :ignore t)
(package! vi-tilde-fringe :ignore t)
(package! solaire-mode :ignore t)
(package! stripe-buffer :ignore t)
(package! git-gutter-fringe :ignore t)
(package! visual-fill-column :ignore t)
(package! centered-window-mode :recipe (:fetcher github :repo "amosbird/centered-window-mode"))
(package! rainbow-mode :recipe (:fetcher github :repo "amosbird/rainbow-mode"))
(package! evil-terminal-cursor-changer :recipe (:fetcher github :repo "amosbird/evil-terminal-cursor-changer"))
(package! evil-textobj-line :recipe (:fetcher github :repo "syohex/evil-textobj-line"))
(package! osc :recipe (:fetcher github :repo "amosbird/osc.el"))
(package! ivy-rich :recipe (:fetcher github :repo "Yevgnen/ivy-rich"))
(package! dired-hacks :recipe (:fetcher github :repo "Fuco1/dired-hacks"))
(package! dired-k :recipe (:fetcher github :repo "amosbird/emacs-dired-k"))
(package! org-mime)
(package! crux)
(package! cnfonts)
(package! chinese-yasdcv)
(package! git-gutter)
(package! evil-nerd-commenter)
(package! narrow-reindent)
(package! fcitx)
(package! sdcv)
(package! pangu-spacing)
(package! counsel-dash)
(package! easy-hugo)
(package! link-hint)
(package! lispyville)
(package! move-text)
(package! ws-butler)
(package! fish-mode)
(package! evil-magit)
(package! eyebrowse)
(package! dired-quick-sort)
(package! highlight-parentheses)
(package! hl-line+)
(package! rainbow-blocks)
(package! ov)
(package! ag)
(package! unfill)
(package! evil-ediff)
(package! yapfify)
(package! emacsql-sqlite)
(package! helm-make)

(package! fill-column-indicator)
(package! gitignore-mode)
(package! magit-svn)
(package! smeargle)
(package! gitconfig-mode)
(package! gitattributes-mode)
(package! git-timemachine)
(package! gitattributes-mode)
(package! gitattributes-mode)

(package! adoc-mode)
(package! page-break-lines)

(package! go-playground)
(package! rust-playground)
(package! cc-playground :recipe (:fetcher github :repo "amosbird/cc-playground"))

(package! pdf-tools)
(package! bind-map)

(package! rainbow-mode)
(package! kurecolor)
